Added create_qpackage() and use_qdata() functions
globalgov/qDatr pull request #46
Opened 2020-10-05 11:09 UTC by henriquesposito

# Description

The create_qpackage() function creates a new package in and consistent with the qDatr ecosystem. 

The use_qdata() facilitates the access to additional data packages from the qDatr ecosystem.  

Closes #45 by adding use_qdata() that sets up data correctly
Closes #44 by adding create_qpackage() that uses own templates

# Checklist:

- [ ] I have commented my code in-line, particularly in hard-to-understand areas
- [ ] My code follows the style guidelines of this project
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have documented any functions or data in the corresponding .R scripts so that roxygen can create documentation
- [ ] The package builds on my OS without issues
- [ ] My changes generate no new warnings
- [ ] PR checks all pass for latest commit
- [ ] I have bumped the version by the appropriate increment in the DESCRIPTION file (major, minor, patch)
- [ ] I have updated NEWS.md
- [ ] I have given this pull request an informative title and description

2020-10-12 18:00 UTC, jhollway requested changes

2020-10-14 12:42 UTC, jhollway requested changes

2020-10-14 12:42 UTC, jhollway commented on R/data.R
> +#' and wragling, consistent with the qDatr ecosystem
Spelling: wragling

2020-10-14 12:42 UTC, jhollway commented on R/data.R
> +#' Create a data folder in the new q package
Actually doesn't create a data folder: `use_qData()` saves an object ready to be lazy-loaded with the package, and creates scripts for documenting and testing that object.

2020-10-14 12:42 UTC, jhollway commented on R/package.R
> +# Helper
Is `user_path_prep()` still necessary?

2020-10-15 07:06 UTC, henriquesposito commented on NAMESPACE
> +importFrom(usethis,create_package)
Should we simply list the usethis as an import rather than importFrom in the package script?

2020-10-15 07:42 UTC, henriquesposito commented on R/data.R
> +use_qData_raw <- function(name = "DATASET", open = rlang::is_interactive()) {
It may be... but if we change to `use_data_raw()` the function name is the same as usethis and I believe some may get confused as well about which one to use.  Maybe simply `qData_raw()` or `use_qDataraw()` are other options... Also, I think it makes sense because we have also the use_qData function and some others that start with a q. What do you think?

2020-10-15 08:09 UTC, henriquesposito commented on R/package.R
> +  # usethis::create_package()
`usethis::create_package()` sets the path to the directory, create an R folder, a standard description document and a namespace. I think this makes to initially set the package and build file-by-file documentation from there. However, we can also do this file-by-file if we want similar to the `create_tidy_package()`. This way we can set the `path <- create_package(path, rstudio = TRUE, open = FALSE)`, like beforehand. Though we may run into "path" issues with this  line as beforehand.

2020-10-15 08:12 UTC, henriquesposito commented on R/package.R
> +            "README.Rmd",
For this I think we may need to also have a READ.md template set up in the templates file. I will do this right now.

2020-10-15 10:38 UTC, henriquesposito commented on inst/templates/qPackage-PR.md
> +- [ ] I have added tests that prove my fix is effective or that my feature works
I do not think it is necessary, but it does not hurt to leave it for the cases where PR is related to bug fixes or that require a function test to be created or modified.

2020-10-15 10:40 UTC, henriquesposito commented on inst/templates/qPackage-PR.md
> +- [ ] My code follows the style guidelines of this project
Yes, it should be enough. Though this may preemptively remind contributors to check for style guidelines and read contributing document.

2020-10-15 15:17 UTC, henriquesposito commented on inst/templates/qPackage-Commands.yml
> +    types: [created]
It appears to be, but only when triggered by the event related to [created]. What we can do is either remove the filter or alter to [edited] or [published].

2020-10-15 15:19 UTC, henriquesposito commented on inst/templates/qPackage-Features.md
> +*If you have a question, please don't use this form. Instead, ask on <https://stackoverflow.com/> or <https://community.rstudio.com/>.*
I do not understand this comment. We need to make the template more qDatr specific or better specify where to ask questions about it?

2020-10-15 15:29 UTC, henriquesposito commented on inst/templates/qPackage-Bugs.md
> +*If you have a question, please don't use this form. Instead, ask on <https://stackoverflow.com/> or <https://community.rstudio.com/>.*
I do not understand this comment. We need to make the template more qDatr specific or better specify where to ask questions about it?

2020-10-15 15:52 UTC, jhollway commented on R/data.R
> +use_qData_raw <- function(name = "DATASET", open = rlang::is_interactive()) {
Added this as new issue for next round.

2020-10-15 16:01 UTC, jhollway approved these changes

2020-10-15 16:20 UTC, merged